name: Hub
main: com.drake.hub.HubMain
version: Snapshot-13.03.16
commands:
   setlobby:
      description: SetLobby
      usage: 
   lobby:
      description: Lobby
      usage: 
   setmotd:
      description: Motd
      usage: 