name: Hub
main: com.drake.hub.HubMain
version: 1.0
commands:
   setlobby:
      description: SetLobby
      usage: 
   sethub:
      description: SetHub
      usage: 
   lobby:
      description: Lobby
      usage: 
   hub:
      description: Hub
      usage: