name: Hub
main: com.drake.hub.HubMain
version: Snapshot-140316
commands:
   setlobby:
      description: SetLobby
      usage: 
   lobby:
      description: Lobby
      usage: 
   setmotd:
      description: Motd
      usage: 
   setOpMotd:
      description: Motd for Op Players
      usage: